version: "2"

services:
  ngnix:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - bookstore
    ports:
      - "80:80"
  bookstore:
    build: .
    command: sh -c 'npm run build &&  npm start'
    ports: 
      - "3001:3000"
    volumes:
      - ./app:/app
    links:
      - MongoDB
    environment:
      DATABASE_URL: mongodb://MongoDB/books
  MongoDB:
    image: mongo:3.4.1
    ports:
      - "27017:27017"
    volumes:
      - /data/mongodb/db:/data/db