version: "2"

volumes:
  service_modules: 
  mongo-data:
    driver: local
    
services:
  ngnix:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - bookstore
    ports:
      - "80:80"
  bookstore:
    container_name: bookstor_server
    build: .
    command: sh -c 'npm start'
    ports:
      - "3001:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
    links:
      - MongoDB
    environment:
      DATABASE_URL: mongodb://MongoDB/books
      PORT: 3000
  MongoDB:
    image: mongo:3.4.1
    volumes:
      - mongo-data:/data/db